//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellerCloud.BusinessRules.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessRulesEngineEntities : DbContext
    {
        public BusinessRulesEngineEntities()
            : base("name=BusinessRulesEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rule> Rule { get; set; }
        public virtual DbSet<RuleArgument> RuleArgument { get; set; }
        public virtual DbSet<RuleModule> RuleModule { get; set; }
        public virtual DbSet<RuleModuleCompanyLink> RuleModuleCompanyLink { get; set; }
    }
}
