//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellerCloud.BusinessRules.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleModuleCompanyLink
    {
        public int Id { get; set; }
        public int IdRuleModule { get; set; }
        public int IdCompany { get; set; }
    
        public virtual RuleModule RuleModule { get; set; }
    }
}
